### ISSUE TITLE
Add "rule of thirds" overlay

### ISSUE THREAD

**Issue by HerrZatacke** [HerrZatacke/2bit-pxlr-studio#4]
Should be possible using sprites

**Comment by reini1305** [comment]
Horizontal lines will be tricky as there can only be 10 sprites on one scanline. Maybe one could show a window or an offscreen area for a single scanline instead.

**Comment by HerrZatacke** [comment]
Or make the line "dashed" so that the number of sprites is enough as well as hiding a bit less of the actual image..

**Comment by HerrZatacke** [comment]
Could work sme way and use same settings variable as #5

**Comment by HerrZatacke** [comment]
Done with 0.9.0
